### PR TITLE
#30 added scm-source commands before building go images

### LINKED ISSUE #30: Add scm-source.json

### PR DESCRIPTION
**Pull request by ChristianLohmann**
fixes #30 

added scm-source commands to create scm-source.json for server and agent images

### CODE REVIEW

**Comment by whiskeysierra** [comment]
We're using those images as base images for our own versions of the go-server and go-agent. Will this cause any issues? Right now we put in our own scm-source.json. What if others do the same without overwriting the file?

**Comment by harti2006** [comment]
I think the commands in the Dockerfiles, that copy the scm-source to the image, are still missing

**Comment by ChristianLohmann** [comment]
ah, you're right. forgot that

**Comment by harti2006** [comment]
@whiskeysierra of course this can always happen. Maybe we need to implement a report in pierone that checks if different artifacts have the same scm-source

**Comment by whiskeysierra** [comment]
> Maybe we need to implement a report in pierone that checks if different artifacts have the same scm-source

Exactly

**Comment by ChristianLohmann** [comment]
@whiskeysierra @harti2006 what would be the result? If the first scm-source.json was already overwritten, we already lost track.

**Comment by whiskeysierra** [comment]
My concern was that people use the image as a base and forgot to overwrite it.

**Comment by ChristianLohmann** [comment]
@whiskeysierra ah, and thats another serious issue.

**Comment by whiskeysierra** [comment]
> ah, and thats another serious issue.

Yes absolutely. Has nothing really to do with stups2go itself.

**Comment by whiskeysierra** [comment]
:+1:

**Pull request merged**
